---
timeout: 1200s
steps:
  # Build WAF image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-waf'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/securely-waf', '.']

  # Push the WAF image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-waf'
    waitFor: ['build-waf']
    args: ['push', 'eu.gcr.io/$PROJECT_ID/securely-waf']

  # Only keep the 10 most recent images
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    waitFor: ['push-waf']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -eou pipefail
        for digest in $(gcloud container images list-tags eu.gcr.io/$PROJECT_ID/securely-waf --limit=99999 \
            --sort-by=TIMESTAMP --format='get(digest)' | head -n-10); do
          gcloud container images delete -q --force-delete-tags "eu.gcr.io/$PROJECT_ID/securely-waf@$${digest}"
        done
